# UNTESTED

MOZ_CFLAGS=-DMOZ_DLL_SUFFIX="\".so\"" `pkg-config --cflags libxul libxul-embedding-unstable mozilla-js`
MOZ_LIBS=`pkg-config --libs libxul libxul-embedding-unstable mozilla-js`

CFLAGS=-fno-rtti -I../common `pkg-config --cflags gtk+-2.0` $(MOZ_CFLAGS)
LDFLAGS=`pkg-config --libs gtk+-2.0` $(MOZ_LIBS) -L../x11 -lmozwebview

all:test

test:test.cpp
	$(CXX) -o $@ $< $(CFLAGS) $(LDFLAGS)


clean:
	rm -f test
